name: turbolingo
description: "A multi-language learning app focused on Japanese."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.0.0
  sqflite: ^2.0.0
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0
  dart_melty_soundfont: ^2.0.0
  flutter_pcm_sound: ^3.3.3
  fl_chart: ^0.60.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  mockito: ^5.0.0
  build_runner: ^2.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/soundfonts/
